version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: team-balancer-backend-prod
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SPREADSHEET_ID=${SPREADSHEET_ID}
    # No volumes in production for better performance and security

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: team-balancer-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5050
    # No volumes in production as we're using a multi-stage build

networks:
  default:
    name: team-balancer-network-prod
