services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: team-balancer-backend-prod
    image: ${REGISTRY_URL}/teammates-suck-backend:${BUILD_TAG}
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SPREADSHEET_ID=${SPREADSHEET_ID}

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      args:
        - VITE_API_BASE_URL=/api
    container_name: team-balancer-frontend-prod
    image: ${REGISTRY_URL}/teammates-suck-frontend:${BUILD_TAG}
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    name: team-balancer-network-prod
