version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: team-balancer-backend-dev
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SPREADSHEET_ID=${SPREADSHEET_ID}
    volumes:
      - ./backend:/app
    command: >
      gunicorn --workers=2 --bind=0.0.0.0:5050 --reload app:app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: team-balancer-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5050
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Use the CMD from the Dockerfile instead of overriding it here

networks:
  default:
    name: team-balancer-network-dev
